### ISSUE TITLE
useProduct

### ISSUE THREAD

**Issue by AdrianRC** [swellstores/swell-sdk#15]
React hook for fetching products and applying helper utilities. 

Example

```typescript
const { product } = useProduct('my-product');
```

In this example `useProduct` will fetch a product with an id or slug of 'my-product' and refetch every time this identifier changes. 

Getting the product's active variation based on the selected options

```typescript
const { variation } = useProduct('my-product', {
  size: 'large',
  color: 'red'
}
```

You can also passed in an existing product that was previously fetched through some other method. This is useful to avoid fetching twice in frameworks like Next.js.

```typescript
 // Product being passed in from a server fetch.
const ProductsPage = ({ product }) => {
  const { variation } = useProduct(product, {
   size: 'large',
   color: 'red'
  }
}
```

Returned properties
- product (SwellProduct)
- loading (boolean)
- error (Error | null)
- variation (SwellProductVariation)

**Comment by cmcollin41** [comment]
@AdrianRC this looks great. Is this ready to start using with the swell UI components?
